# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Statistiline andmeteadus ja visualiseerimine
tagline:          MTMS.01.100
url:              http://andmeteadus.github.io
paginate:         1
baseurl:          /
author:
  name:           Tanel
  url:            
  email:          andmeteadus@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           http://andmeteadus.github.io/

pages_list:       
  About: '/about'
  Projects: '/projects'
  Feed: '/atom.xml'